//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormsApp8.Properties {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinFormsApp8.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _1625943511_tulumba_tatlisi {
            get {
                object obj = ResourceManager.GetObject("1625943511-tulumba-tatlisi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _199843325_cancel_payment_icon_outline_vector_card_error_money_debit {
            get {
                object obj = ResourceManager.GetObject("199843325-cancel-payment-icon-outline-vector-card-error-money-debit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _28395661_kullanıcı_adam_simge {
            get {
                object obj = ResourceManager.GetObject("28395661-kullanıcı-adam-simge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _5164023 {
            get {
                object obj = ResourceManager.GetObject("5164023", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _662adfff_67f4_4311_88c9_bfecab9d8976 {
            get {
                object obj = ResourceManager.GetObject("662adfff-67f4-4311-88c9-bfecab9d8976", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _8010001_yan_fb0c69_1650x1650 {
            get {
                object obj = ResourceManager.GetObject("8010001_yan-fb0c69-1650x1650", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _8030000_yan_881eaf_1650x1650 {
            get {
                object obj = ResourceManager.GetObject("8030000_yan-881eaf-1650x1650", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _83947224_tatlı_kek_tatlı_simgesi_vektör_resim_grafik_tasarım {
            get {
                object obj = ResourceManager.GetObject("83947224-tatlı-kek-tatlı-simgesi-vektör-resim-grafik-tasarım", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _83fa77c907b5df842e69f8d9a3c80a54c2fcf897 {
            get {
                object obj = ResourceManager.GetObject("83fa77c907b5df842e69f8d9a3c80a54c2fcf897", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _89282895_stüdyo_arka_planı_soyut_smooth_dark_blue_with_black_vignette_stüdyo_arka_plan_iş_raporu_dijital {
            get {
                object obj = ResourceManager.GetObject("89282895-stüdyo-arka-planı-soyut-smooth-dark-blue-with-black-vignette-stüdyo-arka" +
                        "-plan-iş-raporu-dijital", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap ayran {
            get {
                object obj = ResourceManager.GetObject("ayran", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap b805051c75b95a8718bde70fa5f35874d79c06c7 {
            get {
                object obj = ResourceManager.GetObject("b805051c75b95a8718bde70fa5f35874d79c06c7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Baklava_1_ {
            get {
                object obj = ResourceManager.GetObject("Baklava(1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Beykent_Universitesi_Logo_Yeni {
            get {
                object obj = ResourceManager.GetObject("Beykent_Universitesi_Logo_Yeni", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap beypazari_soda_200ml {
            get {
                object obj = ResourceManager.GetObject("beypazari-soda-200ml", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap caprisun_multivitamin {
            get {
                object obj = ResourceManager.GetObject("caprisun-multivitamin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap depositphotos_158349438_stock_photo_cashier_machine_or_cash_register {
            get {
                object obj = ResourceManager.GetObject("depositphotos_158349438-stock-photo-cashier-machine-or-cash-register", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap download {
            get {
                object obj = ResourceManager.GetObject("download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap download1 {
            get {
                object obj = ResourceManager.GetObject("download1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap download2 {
            get {
                object obj = ResourceManager.GetObject("download2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap download3 {
            get {
                object obj = ResourceManager.GetObject("download3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap etli_bugdayli_yogurt_corbasi {
            get {
                object obj = ResourceManager.GetObject("etli-bugdayli-yogurt-corbasi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap ezogelin_corbasi {
            get {
                object obj = ResourceManager.GetObject("ezogelin-corbasi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap hq720 {
            get {
                object obj = ResourceManager.GetObject("hq720", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap img_3336_1 {
            get {
                object obj = ResourceManager.GetObject("img_3336_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap indir {
            get {
                object obj = ResourceManager.GetObject("indir", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_917734984_612x612 {
            get {
                object obj = ResourceManager.GetObject("istockphoto-917734984-612x612", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap login_icon_in_trendy_flat_style_isolated_on_white_background_approach_symbol_for_your_web_site_design_logo_app_ui_illustration_eps10_flat_style_for_graphic_design_vector {
            get {
                object obj = ResourceManager.GetObject("login-icon-in-trendy-flat-style-isolated-on-white-background-approach-symbol-for-" +
                        "your-web-site-design-logo-app-ui-illustration-eps10-flat-style-for-graphic-desig" +
                        "n-vector", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap lovepik_large_data_technology_line_background_image_400124958 {
            get {
                object obj = ResourceManager.GetObject("lovepik-large-data-technology-line-background-image_400124958", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap makarna {
            get {
                object obj = ResourceManager.GetObject("makarna", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap McDonald_s_Quarter_Pounder_with_Cheese__United_States {
            get {
                object obj = ResourceManager.GetObject("McDonald\'s_Quarter_Pounder_with_Cheese,_United_States", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap menu_01 {
            get {
                object obj = ResourceManager.GetObject("menu-01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap partiterra1 {
            get {
                object obj = ResourceManager.GetObject("partiterra1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_computer_icons_collegest_order_icon_cdr_angle {
            get {
                object obj = ResourceManager.GetObject("png-clipart-computer-icons-collegest-order-icon-cdr-angle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_miso_soup_computer_icons_food_indian_cuisine_soup_pot_soup_food {
            get {
                object obj = ResourceManager.GetObject("png-clipart-miso-soup-computer-icons-food-indian-cuisine-soup-pot-soup-food", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_chef_cooking_computer_icons_kitchen_recipe_cooking_microphone_logo_cook {
            get {
                object obj = ResourceManager.GetObject("png-transparent-chef-cooking-computer-icons-kitchen-recipe-cooking-microphone-log" +
                        "o-cook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_computer_icons_undo_arrow_button_circular_angle_text_monochrome_thumbnail {
            get {
                object obj = ResourceManager.GetObject("png-transparent-computer-icons-undo-arrow-button-circular-angle-text-monochrome-t" +
                        "humbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_credit_card_payment_trade_computer_icons_card_symbol_text_rectangle_payment_thumbnail {
            get {
                object obj = ResourceManager.GetObject("png-transparent-credit-card-payment-trade-computer-icons-card-symbol-text-rectang" +
                        "le-payment-thumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_dining_menu_cafe_menu_restaurant_icon_restaurant_menu_template_white_food_thumbnail {
            get {
                object obj = ResourceManager.GetObject("png-transparent-dining-menu-cafe-menu-restaurant-icon-restaurant-menu-template-wh" +
                        "ite-food-thumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_exit_sign_exit_sign_orange_circle_stock_photography {
            get {
                object obj = ResourceManager.GetObject("png-transparent-exit-sign-exit-sign-orange-circle-stock-photography", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_fizzy_drinks_non_alcoholic_drink_computer_icons_soft_drink_food_rectangle_drinking_straw {
            get {
                object obj = ResourceManager.GetObject("png-transparent-fizzy-drinks-non-alcoholic-drink-computer-icons-soft-drink-food-r" +
                        "ectangle-drinking-straw", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_green_check_illustration_check_mark_checkbox_yes_miscellaneous_angle_hand_thumbnail {
            get {
                object obj = ResourceManager.GetObject("png-transparent-green-check-illustration-check-mark-checkbox-yes-miscellaneous-an" +
                        "gle-hand-thumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_sales_computer_icons_purchasing_e_commerce_selling_miscellaneous_angle_text {
            get {
                object obj = ResourceManager.GetObject("png-transparent-sales-computer-icons-purchasing-e-commerce-selling-miscellaneous-" +
                        "angle-text", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_sales_computer_icons_purchasing_e_commerce_selling_miscellaneous_angle_text1 {
            get {
                object obj = ResourceManager.GetObject("png-transparent-sales-computer-icons-purchasing-e-commerce-selling-miscellaneous-" +
                        "angle-text1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_table_matbord_computer_icons_furniture_dining_room_restaurant_table_furniture_text_logo {
            get {
                object obj = ResourceManager.GetObject("png-transparent-table-matbord-computer-icons-furniture-dining-room-restaurant-tab" +
                        "le-furniture-text-logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_vegetable_snow_pea_bean_green_bean_green_pea_stir_frying_cartoon_common_bean_thumbnail {
            get {
                object obj = ResourceManager.GetObject("png-transparent-vegetable-snow-pea-bean-green-bean-green-pea-stir-frying-cartoon-" +
                        "common-bean-thumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_restaurant_view_through_table_texture_image_13818636 {
            get {
                object obj = ResourceManager.GetObject("pngtree-restaurant-view-through-table-texture-image_13818636", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_there_is_an_oldstyle_cashier_counter_inside_several_shelves_image_2541445 {
            get {
                object obj = ResourceManager.GetObject("pngtree-there-is-an-oldstyle-cashier-counter-inside-several-shelves-image_2541445" +
                        "", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap tavukgogusutari1 {
            get {
                object obj = ResourceManager.GetObject("tavukgogusutari1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap tavuklu_pilav_47 {
            get {
                object obj = ResourceManager.GetObject("tavuklu-pilav-47", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
